import p1 from "../assets/images/pr1.jpg";
import p2 from "../assets/images/pr2.jpg";
import p3 from "../assets/images/pr3.jpg";
import p4 from "../assets/images/pr4.jpg";

export const categoryImages = {
  "New Arrivals": p1,
  "Best Offers": p2,
  "Live Plants": p3,
  "Starters": p4,
  "Aquarium Essentials": p1,
  "Aquarium Food": p2,
  "Aquarium Filters": p3,
  "Aquarium Supplyment": p4,
  "Aquarium Tanks": p1,
  "Aquarium Lights": p2,
  "Aquarium Driftwoods": p3,
  "Aquarium Toys": p4
};

export const aquariumProducts = [
  // 🌿 New Arrivals (5 products)
  {
    id: 1,
    name: "Nano Aquarium Tank (5 Gallons)",
    price: 49.99,
    offerPrice: 39.99,
    stock: 15,
    categories: ["New Arrivals", "Aquarium Tanks"],
    images: [p1, p2, p3, p4],
    description: "Compact and stylish glass tank perfect for bettas or shrimp.",
  },
  {
    id: 2,
    name: "Smart LED Aquarium Light Pro",
    price: 89.99,
    offerPrice: 69.99,
    stock: 8,
    categories: ["New Arrivals", "Aquarium Lights"],
    images: [p1, p2, p3, p4],
    description: "App-controlled RGB light with sunrise/sunset modes.",
  },
  {
    id: 3,
    name: "Self-Cleaning Aquarium (10L)",
    price: 129.99,
    offerPrice: 99.99,
    stock: 5,
    categories: ["New Arrivals", "Aquarium Tanks"],
    images: [p1, p2, p3, p4],
    description: "Innovative tank with built-in filtration system.",
  },
  {
    id: 4,
    name: "AquaForest Plant Bundle",
    price: 34.99,
    offerPrice: 29.99,
    stock: 12,
    categories: ["New Arrivals", "Live Plants"],
    images: [p1, p2, p3, p4],
    description: "Curated selection of 5 rare aquatic plants.",
  },
  {
    id: 5,
    name: "Magnetic Algae Scrubber",
    price: 19.99,
    offerPrice: 14.99,
    stock: 20,
    categories: ["New Arrivals", "Aquarium Essentials"],
    images: [p1, p2, p3, p4],
    description: "Effortlessly clean glass without wetting your hands.",
  },


  // 🔥 Best Offers (4 products)
  {
    id: 6,
    name: "Hang-On Back Filter (200L/H)",
    price: 29.99,
    offerPrice: 19.99,
    stock: 30,
    categories: ["Best Offers", "Aquarium Filters"],
    images: [p1, p2, p3, p4],
    description: "Efficient and quiet filtration for small to medium tanks.",
  },
  {
    id: 7,
    name: "Betta Fish Food (50g)",
    price: 9.99,
    offerPrice: 6.99,
    stock: 50,
    categories: ["Best Offers", "Aquarium Food"],
    images: [p1, p2, p3, p4],
    description: "High-protein pellets for vibrant betta fish.",
  },
  {
    id: 8,
    name: "API Freshwater Test Kit",
    price: 34.99,
    offerPrice: 29.99,
    stock: 18,
    categories: ["Best Offers", "Aquarium Essentials"],
    images: [p1, p2, p3, p4],
    description: "Measures pH, ammonia, nitrites, and nitrates.",
  },
  {
    id: 9,
    name: "Starter Heater (50W)",
    price: 24.99,
    offerPrice: 16.99,
    stock: 10,
    categories: ["Best Offers", "Starters"],
    images: [p1, p2, p3, p4],
    description: "Reliable heater for 5-10 gallon tanks.",
  },
  {
    id: 9,
    name: "Heater (100W)",
    price: 24.99,
    offerPrice: 16.99,
    stock: 10,
    categories: ["Best Offers", "Starters"],
    images: [p1, p2, p3, p4],
    description: "Reliable heater for 5-10 gallon tanks.",
  },
  {
    id: 6,
    name: "Hang-On Back Filter (200L/H)",
    price: 29.99,
    offerPrice: 19.99,
    stock: 30,
    categories: ["Best Offers", "Aquarium Filters"],
    images: [p1, p2, p3, p4],
    description: "Efficient and quiet filtration for small to medium tanks.",
  },
  {
    id: 7,
    name: "Betta Fish Food (50g)",
    price: 9.99,
    offerPrice: 6.99,
    stock: 50,
    categories: ["Best Offers", "Aquarium Food"],
    images: [p1, p2, p3, p4],
    description: "High-protein pellets for vibrant betta fish.",
  },
  {
    id: 8,
    name: "API Freshwater Test Kit",
    price: 34.99,
    offerPrice: 29.99,
    stock: 18,
    categories: ["Best Offers", "Aquarium Essentials"],
    images: [p1, p2, p3, p4],
    description: "Measures pH, ammonia, nitrites, and nitrates.",
  },
  {
    id: 9,
    name: "Starter Heater (50W)",
    price: 24.99,
    offerPrice: 16.99,
    stock: 10,
    categories: ["Best Offers", "Starters"],
    images: [p1, p2, p3, p4],
    description: "Reliable heater for 5-10 gallon tanks.",
  },
  {
    id: 9,
    name: "Heater (100W)",
    price: 24.99,
    offerPrice: 16.99,
    stock: 10,
    categories: ["Best Offers", "Starters"],
    images: [p1, p2, p3, p4],
    description: "Reliable heater for 5-10 gallon tanks.",
  },

  // 🌱 Live Plants (3 products)
  {
    id: 10,
    name: "Java Fern (Bundle)",
    price: 12.99,
    offerPrice: 9.99,
    stock: 20,
    categories: ["Live Plants", "Starters"],
    images: [p1, p2, p3, p4],
    description: "Low-maintenance plant ideal for beginners.",
  },
  {
    id: 11,
    name: "Anubias Nana (Potted)",
    price: 14.99,
    offerPrice: 11.99,
    stock: 15,
    categories: ["Live Plants", "Aquarium Essentials"],
    images: [p1, p2, p3, p4],
    description: "Hardy plant that thrives in low-light tanks.",
  },
  {
    id: 12,
    name: "Dwarf Hairgrass (Carpet)",
    price: 18.99,
    offerPrice: 15.99,
    stock: 8,
    categories: ["Live Plants", "Aquarium Essentials"],
    images: [p1, p2, p3, p4],
    description: "Creates a lush green carpet in planted tanks.",
  },

  // 🐠 Starters (2 products)
  {
    id: 13,
    name: "Beginner Fish Kit (10L)",
    price: 69.99,
    offerPrice: 59.99,
    stock: 12,
    categories: ["Starters", "Aquarium Kits"],
    images: [p1, p2, p3, p4],
    description: "Everything needed to start a freshwater aquarium.",
  },
  {
    id: 14,
    name: "Neon Tetra School (6 Fish)",
    price: 22.99,
    offerPrice: 19.99,
    stock: 5,
    categories: ["Starters", "Aquarium Supplyment"],
    images: [p1, p2, p3, p4],
    description: "Hardy and colorful beginner-friendly fish.",
  },

  // ⚙️ Aquarium Essentials (3 products)
  {
    id: 15,
    name: "Gravel Vacuum Cleaner",
    price: 19.99,
    offerPrice: 15.99,
    stock: 25,
    categories: ["Aquarium Essentials"],
    images: [p1, p2, p3, p4],
    description: "Easy water changes and substrate cleaning.",
  },
  {
    id: 16,
    name: "Aquarium Thermometer (Digital)",
    price: 12.99,
    offerPrice: 9.99,
    stock: 30,
    categories: ["Aquarium Essentials"],
    images: [p1, p2, p3, p4],
    description: "Accurate temperature monitoring with LCD display.",
  },
  {
    id: 17,
    name: "Water Conditioner (250ml)",
    price: 14.99,
    offerPrice: 11.99,
    stock: 40,
    categories: ["Aquarium Essentials", "Aquarium Supplyment"],
    images: [p1, p2, p3, p4],
    description: "Removes chlorine and detoxifies heavy metals.",
  },

  // 🎣 Decor & Toys (3 products)
  {
    id: 18,
    name: "Natural Driftwood (Medium)",
    price: 22.99,
    offerPrice: 18.99,
    stock: 8,
    categories: ["Aquarium Driftwoods"],
    images: [p1, p2, p3, p4],
    description: "Adds a natural look and hiding spots for fish.",
  },
  {
    id: 19,
    name: "Bubble Wall Decor (30cm)",
    price: 16.99,
    offerPrice: 12.99,
    stock: 15,
    categories: ["Aquarium Toys"],
    images: [p1, p2, p3, p4],
    description: "Creates mesmerizing oxygen bubbles.",
  },
  {
    id: 20,
    name: "Sunken Ship Ornament",
    price: 24.99,
    offerPrice: 19.99,
    stock: 10,
    categories: ["Aquarium Toys"],
    images: [p1, p2, p3, p4],
    description: "Fun pirate-themed decor with hiding caves.",
  },
];

export default aquariumProducts;